### ISSUE TITLE
Failing on NixOS

### ISSUE THREAD

**Issue by maxdevjs** [vilmibm/gh-contribute#7]
I found three issues on my system ([NixOS](https://nixos.org/)) related to this extension so far:

- the used shebang (`#!/bin/bash`) fails ([NixOS](https://nixos.org/) and other flavors do not have `bash` in such location)
  - with #6 the [portability](https://en.wikipedia.org/w/index.php?title=Shebang_(Unix)&oldid=878552871#Portability) should be more reliable
    - I also sent https://github.com/vilmibm/gh-screensaver/pull/13 for the same reason 

- specific to [gh-contribute](https://github.com/vilmibm/gh-contribute)
  - after replacing the shebang
    - the invocation (`gh contribute ...`) is successful
      - but, then, `bin/linux-x86_64-v1.0.2` fails to execute: `$HOME/.local/share/gh/extensions/gh-contribute/gh-contribute: line 54: $HOME/.local/share/gh/extensions/gh-contribute/bin/linux-x86_64-v1.0.2: No such file or directory`
        - this basically should mean that the executable is not patched for [NixOS](https://nixos.org/)
          - as, if I compile locally, it works

This is somewhat weird as, for example, [gh-screensaver](https://github.com/vilmibm/gh-screensaver) works after replacing the shebang.

At the moment, I do not know what the difference between the two extensions is.
Especially, I am not sure why [gh-screensaver](https://github.com/vilmibm/gh-screensaver) works even if the two install scripts are basically the same!

Currently `gh-contribute`:

- checks if the extension executable is not executable
- as the extension executable **is not** executable (absent or...)
- downloads an executable that surely is not executable on [NixOS](https://nixos.org/) (probably because it is not patched)

I know zero of Go and Go on [NixOS](https://nixos.org/) then I can not assure that my assumption is right (principally why this extension executable should, apparently, be patched).

**But**, I changed the logic of `gh-contribute` and I can now successfully build from an initial `gh contribute` and the executable runs. This should prove that the downloaded extension does not work because not patched(!), not built for NixOS.

I will clean the script and post for review.

I also checked 

- [gh-user-status](https://github.com/vilmibm/gh-user-status) and behaves as this extension (fails without local build)
- [gh-markdown-preview](https://github.com/yusukebe/gh-markdown-preview) works out of the box (uses `#!/usr/bin/env bash`)

Any suggestion about what part could influence the behavior, is welcome.

Anyway:

- after successfully compiling and running this extension
  - does not matter how I invoke it
    - I always get an ``Unable to find a good issue to suggest :( try perusing the repository with `gh issue list`.``
      - opposed to what I see in [Using the GitHub CLI to find good-first-issue #Shorts](https://www.youtube.com/shorts/aBOXL95zqMM?&ab_channel=GitHub)

**Comment by maxdevjs** [comment]
I confirm that some (and not only) Go extensions can fail on NixOS (and most likely, on other non FHS compliant systems - perhaps Guix).

Following a NixOS case (all the extensions should be compiled locally to be 'patched' and consequenly work). Right now the installation script:

- verifies if can assign an `exe` identifier for a specific platform
  - otherwise it compiles it for the specific platform
    - this arises an issue, as
      - on NixOS, will be found a specific platform
        - then the extension will **not** be compiled 
          - and most (all, as it would be extremely complicated to figure out if an extension needs or not to be patched (meaning that are depending on `/libs`, not being statically compiled, depending on libraries written in other languages, etc))
            - should be compiled locally to be 'patched' and consequently work
- the unfortunate point is then the check if an extension can or can not be executed
  - if not, then will be downloaded
    - rabbit hole mode
      - the downloaded extension will likely **never** be executable (on NixOS, remember?)
        - not being patched

Okay, at the moment I have no idea how this extension world works: if there is or not a source of truth to which every extension author would refer.

Thereby I chose @vilmibm as an author for this brainstorm.

The installation script(s) should be kindly patched. And the word spread :)

If there will be interest in solving/soften the situation, I will open an issue proposing a slightly different script workflow.

**Comment by vilmibm** [comment]
Thanks for the thorough debugging. I've moved this to use the newer precompilation strategy so there is no more glue bash script to contend with. In theory this should help, so I'm closing this issue.
