### ISSUE TITLE
gh-contribute/bin/cmd.out: No such file or directory

### ISSUE THREAD

**Issue by andypiper** [vilmibm/gh-contribute#8]
This looks to be the [same issue as on the gh-user-status extension](https://github.com/vilmibm/gh-user-status/issues/2) (it also exists on gh-screensaver, locally for me). Could be a Go thing, since they are all written in Go?

```
$ ls /Users/andypiper/.local/share/gh/extensions/gh-contribute
CONTRIBUTING.md README.md       gh-contribute   go.sum          release.sh
LICENSE         cmd.out         go.mod          main.go
```

Looks like the `cmd.out` file is not ending up in the `bin` directory for the extension, for whatever reason.

**Comment by vilmibm** [comment]
reopen if still happening as of v1.1.1
